import '../styles/globals.css';
import Head from 'next/head';
import { ThemeProvider } from 'styled-components';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';

import AppContext from 'components/AppContext';
import { theme } from 'components/theme';

function MyApp({ Component, pageProps }: any) {
  const queryClient = new QueryClient();

  // Creates a custom layout function to use custom layout across application
  const getLayout = Component.getLayout || ((page: any) => <>{page}</>);

  return (
    <>
      <Head>
        <title>Future Exercise Lookup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <QueryClientProvider client={queryClient}>
          <AppContext>{getLayout(<Component {...pageProps} />)}</AppContext>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
